version: '3'

services:
  frontend:
    build: ./
    image: chansopheaktra/vue-school:latest
    ports: 
      - "8000:8000"
    container_name: frontend-docker
    restart: always
    links:
      - backend

  backend:
    build: ./
    image: chansopheaktra/api-school:latest
    ports:
      - "9090:9090"
    container_name: backend-docker
    restart: always
    links:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    ports: 
      - "5432:5432"
    container_name: database-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: school
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data